// NOTES
export const NOTES_SET_NOTES = 'NOTES_SET_NOTES'
export const NOTES_TOOGLE_BOOKED = 'NOTES_TOOGLE_BOOKED'
export const NOTES_DELETE_NOTE = 'NOTES_DELETE_NOTE'
export const NOTES_ADD_NOTE = 'NOTES_ADD_NOTE'
export const NOTES_SET_LOADING = 'NOTES_ADD_NOTE'
export const NOTES_CHANGE_FILTER = 'NOTES_CHANGE_FILTER'
export const NOTES_EDIT_NOTE = 'NOTES_EDIT_NOTE'